spring.application.name=backend

spring.datasource.url=jdbc:postgresql://localhost:5432/ai_backend
spring.datasource.username=backend
spring.datasource.password=backend
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true